from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime


def generate_docx(content: dict, output_path: str, doc_type: str = "SOW"):
    doc = Document()

    # ── Styles ──────────────────────────────────────────────────────────────
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    # Cover page
    _add_cover(doc, doc_type, content)

    # Table of contents placeholder
    doc.add_page_break()
    toc = doc.add_paragraph("Table of Contents")
    toc.style = doc.styles["Heading 1"]

    doc.add_page_break()

    # Sections
    for section_key, section_value in content.items():
        if section_key.startswith("_"):
            continue
        _add_section(doc, section_key, section_value)

    # Footer with date
    _add_footer(doc)

    doc.save(output_path)


def _add_cover(doc: Document, doc_type: str, content: dict):
    doc.add_paragraph()
    doc.add_paragraph()

    title = doc.add_paragraph(doc_type)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.runs[0].font.size = Pt(36)
    title.runs[0].font.bold = True
    title.runs[0].font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

    subtitle = doc.add_paragraph("Business Analyst Agent — Invuric")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.size = Pt(14)
    subtitle.runs[0].font.color.rgb = RGBColor(0x64, 0x64, 0x80)

    doc.add_paragraph()

    date_para = doc.add_paragraph(datetime.utcnow().strftime("%B %d, %Y"))
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_para.runs[0].font.color.rgb = RGBColor(0x64, 0x64, 0x80)


def _add_section(doc: Document, key: str, value):
    # Convert snake_case / camelCase key to Title Case heading
    heading_text = key.replace("_", " ").replace("-", " ").title()
    heading = doc.add_heading(heading_text, level=1)
    heading.runs[0].font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

    if isinstance(value, str):
        doc.add_paragraph(value)

    elif isinstance(value, list):
        for item in value:
            if isinstance(item, dict):
                _add_dict_block(doc, item)
            else:
                para = doc.add_paragraph(style="List Bullet")
                para.add_run(str(item))

    elif isinstance(value, dict):
        _add_dict_block(doc, value)

    doc.add_paragraph()


def _add_dict_block(doc: Document, data: dict):
    for k, v in data.items():
        para = doc.add_paragraph()
        label = para.add_run(f"{k.replace('_', ' ').title()}: ")
        label.bold = True
        para.add_run(str(v) if not isinstance(v, list) else ", ".join(str(x) for x in v))


def _add_footer(doc: Document):
    for section in doc.sections:
        footer = section.footer
        footer_para = footer.paragraphs[0]
        footer_para.text = f"Generated by Invuric BA Agent · {datetime.utcnow().strftime('%Y-%m-%d')}"
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
